name: "Deploy embed script"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "hi"
      - name: DOnot know
        run: echo "CHECKING PUSH AGAIN"