name: "Deploy embed script"

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pipeline
        run: echo "hi"
      - name: Donot know
        run: echo "CHECKING PUSH AGAIN"
      - name: saving private key to SERVER
        run: echo "${{ secrets.SSH_KEY }}" &> ~/ssh_key
      - name: sshing to server
        run: ssh -i ~/ssh_key ubuntu@52.64.188.144
      - name: list directory
        run: ls 