name: Deploy to staging
on:
    push:
        branches:
            -main
jobs:
    deploy:
        runs-on: ubuntu-latest
    
        steps:
            -   name: everything ig
                run: echo "hi";